<?php
/**
 * @file
 *  Display Livefyre comments.
 */

/**
 * Define the zor library Livefyre will pull down from.
 */
define('LF_ZOR', 'http://zor.livefyre.com/wjs/v3.0/javascripts/livefyre.js');

/**
 * Include the Livefyre API
 */
include_once 'livefyre-api/libs/php/Livefyre.php';

/**
 * Implements hook_help().
 */
function livefyre_help($path, $arg) {
  switch ($path) {
    case 'admin/help#livefyre':
      return '<p>' . t('Implements Livefyre Comments 3') . '</p>';
      break;
  }
}

/**
 * Implements hook_menu().
 */
function livefyre_menu() {
  $items = array();

  $items['admin/config/livefyre'] = array(
    'title' => 'Livefyre',
    'description' => 'Configure livefyre comments',
    'access arguments' => array('administer livefyre comments'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('livefyre_admin_settings_form'),
    'file' => 'livefyre.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function livefyre_permission() {
  return array(
    'administer livefyre comments' => array(
      'title' => t('Administer Livefyre Comments'),
      'description' => t('Allow a user to administer Livefyre Comments.'),
    ),
    'add livefyre html' => array(
      'title' => t('Add Livefyre HTML'),
      'description' => t('Allow a user to add "extra" html, js and/or css which doesn\'t have to originate from Livefyre.'),
    ),
    'access livefyre comments' => array(
      'title' => t('Access Livefyre comments'),
      'description' => t('Use Livefyre comments on the site.'),
    ),
    'bypass livefyre comments visibility settings' => array(
      'title' => t('Bypass Livefyre comments visibility settings'),
      'description' => t('Show Livefyre comment fields, regardless of the field settings.'),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function livefyre_block_info() {
  return array(
    'livefyre_comments' => array(
      'info' => t('Livefyre Comments'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_field_info().
 */
function livefyre_field_info() {
  return array(
    'livefyre' => array(
      'label' => t('Livefyre'),
      'description' => t('This field stores that the Livefyre comment is enabled or not.'),
      'default_widget' => 'livefyre_checkbox',
      'default_formatter' => 'livefyre_full',
      'instance_settings' => array(
        'livefyre_settings_hide' => 0,
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function livefyre_field_formatter_info() {
  return array(
    'livefyre_full' => array(
      'label' => t('Full'),
      'description' => t('Shows the full comment stream'),
      'field types' => array('livefyre'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function livefyre_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);

  // Generate the article id from the current entity and entity ID. Use the
  // entity's url instead of type:id because it will easier to handle in the
  // block implementation.
  $article_id = entity_uri($entity_type, $entity);
  $article_id = $article_id['path'];

  switch ($display['type']) {
    case 'livefyre_full':
      foreach ($items as $delta => $item) {
        if ($item['value']) {
          $element[$delta] = array(
            '#theme' => 'livefyre_formatter_full',
            '#entity' => $entity,
            '#article_id' => $article_id,
            '#widget_id' => "livefyre-entity-{$entity_type}-id-{$id}-field-{$field['id']}-{$delta}",
            '#title' => isset($entity->title) ? $entity->title : drupal_get_title(),
          );
        }
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_theme().
 */
function livefyre_theme($existing, $type, $theme, $path) {
  return array(
    'livefyre_formatter_full' => array(
      'variables' => array(
        'entity' => new stdClass(),
        'article_id' => '',
        'widget_id' => '',
        'title' => '',
      )
    ),
  );
}

/**
 * Renders livefyre field's full formatter.
 */
function theme_livefyre_formatter_full(&$variables) {
  // Custom delegate object if this is and enterprise customer.
  $delegate = livefyre_is_enterprise() ? 'authDelegate' : '';

  livefyre_page_setup();

  $out = livefyre_get_bootstrapped_data($variables['article_id'], '<div id="' . $variables['widget_id'] . '">');

  // Add JS libs.
  module_load_include('inc', 'livefyre', 'livefyre-enterprise-code');
  $conv = livefyre_build_conv($variables['article_id'], $variables['title']);
  $output = $conv->to_initjs_v3($variables['widget_id'], $delegate);
  $cleansed_tags = str_replace('<script type="text/javascript">', "", $output);
  $cleansed_tags = str_replace('</script>', "", $cleansed_tags);
  livefyre_add_footer($cleansed_tags);

  // Return with the id. If the bootstrap exists it will contain the generated
  // html data too for search engines.
  return $out;
}
